# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URI: process.env.MONGODB_URI
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: process.env.MONGODB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: process.env.MONGODB_ROOT_PASSWORD
    volumes:
      - mongodb-data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017

volumes:
  mongodb-data:

