name: Manual Deployment to Digital Ocean

on:
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com/nomadiq
          username: ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.digitalocean.com/nomadiq/my-app:latest
      - name: Decode SSH Key and Deploy to Droplet
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DROPLET_SSH_KEY }}" | base64 --decode > $HOME/decoded_ssh_key
          chmod 600 $HOME/decoded_ssh_key
          ssh-add $HOME/decoded_ssh_key
          ssh-add -L
          echo "${{ secrets.DEV_ENV_FILE }}" > $HOME/.env
          ssh -o StrictHostKeyChecking=no -i $HOME/decoded_ssh_key ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} << EOF
            docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }} --password-stdin <<< ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            docker pull registry.digitalocean.com/nomadiq/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 8080:3000 --env-file $HOME/.env registry.digitalocean.com/nomadiq/my-app:latest
          EOF
        shell: bash