name: CI

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            yarn.lock

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Run lint
        run: npm run lint

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      
      - name: Install jest
        run: npm install jest --save-dev

      - name: Run tests
        run: npm run test

