name: CI

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    types:
      - opened
    branches:
      - main
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.8.0'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            yarn.lock

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.8.0'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run tests
        run: npm test
        working-directory: ./build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy
        run: |
          echo "Deploying to production..."
        working-directory: ./build
